/*
 * generated by Xtext 2.19.0
 */
package org.xtext.csmLab.symboleo.ide


/**
 * Use this class to register ide components.
 */
class SymboleoIdeModule extends AbstractSymboleoIdeModule {
}
