/*
 * generated by Xtext 2.25.0
 */
package ca.uottawa.csmlab.symboleo;

import org.eclipse.xtext.conversion.IValueConverterService;

import ca.uottawa.csmlab.symboleo.validation.SymboleoValueConverters;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SymboleoRuntimeModule extends AbstractSymboleoRuntimeModule {
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return SymboleoValueConverters.class;
  }
}
