/*
 * generated by Xtext 2.25.0
 */
package ca.uottawa.csmlab.symboleo;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SymboleoStandaloneSetup extends SymboleoStandaloneSetupGenerated {

	public static void doSetup() {
		new SymboleoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
