/*
 * generated by Xtext 2.19.0
 */
package org.xtext.csmLab.symboleo


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SymboleoRuntimeModule extends AbstractSymboleoRuntimeModule {
}
