/*
 * generated by Xtext 2.19.0
 */
package org.xtext.csmLab.symboleo


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SymboleoStandaloneSetup extends SymboleoStandaloneSetupGenerated {

	def static void doSetup() {
		new SymboleoStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
