/*
 * generated by Xtext 2.25.0
 */
package ca.uottawa.csmlab.symboleo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SymboleoUiModule extends AbstractSymboleoUiModule {

	public SymboleoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
